# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ms-ecurrent-account

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://everisbank.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_001744526f624bcc86055394f9b77771 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8821173b7bd049deb94f77e6e1b0916e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_001744526f624bcc86055394f9b77771 }}/bc-currentaccounts-enterprise:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ms-ecurrent-account'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d778d87654344389b8a44e8051fbb4af }}
        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_001744526f624bcc86055394f9b77771 }}/bc-currentaccounts-enterprise:${{ github.sha }}'